export const stateInitial = {   
    actionProps: 0, 
    montoLocal: "0.00",
    montoLocalError: false,
    montoLocalErrorText: '',
    montoLocalErrorHide: 'hide',    
    montoDivisa: "0.00",
    montoDivisaError: false,
    montoDivisaErrorText: '',
    montoDivisaErrorHide: 'hide',    
    formaPagoLocal: null,
    formaPagoLocalError: "",
    formaPagoLocalTextError: "",
    formaPagoLocalHide: "hide",
    formaPagoDivisa: null,
    formaPagoDivisaError: "",
    formaPagoDivisaTextError: "",
    formaPagoDivisaHide: "hide",
    montoPartial: "0.00",
    montoPartialError: false,
    montoPartialErrorText: '',
    montoPartialErrorHide: 'hide',    
    montoConversionDivisa: '0.00',
}