export const stateInitial = {
    loading: 'show',
    actionReducer: 0,
    
    name: "",
    nameError: false,
    nameTextError: '',
    nameHide: 'hide',

    arrayType: null,
    arrayTypeError: '',
    arrayTypeTextError: '',
    arrayTypeHide: 'hide',

    valueDiscount: '0.00',
    valueDiscountError: false,
    valueDiscountTextError: "",
    valueDiscountHide: "hide",

    startDate: new Date(),
    startDateError: "",
    startDateTextError: '',
    startDateHide: 'hide',

    endDate: new Date(),
    endDateError: "",
    endDateTextError: '',
    endDateHide: 'hide',

    collapseProducts: false,
    tableProductsTextError: '',
    collapseServices: false,
    tableServicesTextError: '',
    collapseAreas: false,
    collapseClass: false,
    collapsePlanes: false,
    collapsePackages: false,
    arrayClass: null,
    arrayClassError: '',
    arrayClassTextError: '',
    arrayClassHide: 'hide',
    arrayPlanes: null,
    arrayPlanesError: '',
    arrayPlanesTextError: '',
    arrayPlanesHide: 'hide',
    arrayPackages: null,
    arrayPackagesError: '',
    arrayPackagesTextError: '',
    arrayPackagesHide: 'hide',
    arrayAreas: null,
    arrayAreasError: '',
    arrayAreasTextError: '',
    arrayAreasHide: 'hide',    
    aplicateAllAreas: false,
    aplicateAllClass: false,
    aplicateAllPlanes: false,
    aplicateAllPackages: false,
    aplicateAllProducts: false,
    aplicateAllServices: false,
}