export const stateInitial = {
    loading: 'show',
    actionReducer: 0,
    name: "",
    nameError: false,
    nameTextError: '',
    nameHide: 'hide',
    description: "",
    descriptionError: false,
    descriptionTextError: '',
    descriptionHide: 'hide',
    arrayDepartaments: null,
    arrayDepartamentsError: "",
    arrayDepartamentsTextError: "",
    arrayDepartamentsHide: "hide",
    belongsDepartament: false,
}