export const estadoInicial = {
    loading: 'show',
    name: '',
    nameError: false,
    nameTextError: '',
    nameHide: 'hide',
    description: '',
    descriptionError: false,
    descriptionTextError: '',
    descriptionHide: 'hide',
    amount: '0.00',
    amountError: false,
    amountTextError: '',
    amountHide: 'hide',
    arrayImpuesto: null,
    arrayImpuestoError: '',
    arrayImpuestoTextError: '',
    arrayImpuestoHide: 'hide',
    corporateGroup: false,
    arrayCycleOptions: [
        {
            label: 'Diario', value: false,
        },
        {
            label: 'Mensual', value: true
        }
    ],
    arrayCycle: null,
    arrayCycleError: '',
    arrayCycleTextError: '',
    arrayCycleHide: 'hide',
    timeCycle: '',
    timeCycleError: false,
    timeCycleTextError: '',
    timeCycleHide: 'hide',
    dateChange: false,


    penalty: false,
    arrayPenalty: null,
    arrayPenaltyError: '',
    arrayPenaltyTextError: '',
    arrayPenaltyHide: 'hide',
    expiration: false,
    expirationDate: new Date(),
    expirationDateError: "",
    expirationDateTextError: '',
    expirationDateHide: 'hide',
    additionalDay: false,
    amountDayAdditional: '0.00',
    amountDayAdditionalError: false,
    amountDayAdditionalTextError: '',
    amountDayAdditionalHide: 'hide',
    flexibility: false,
    flexibilityDay: '',
    flexibilityDayError: false,
    flexibilityDayTextError: '',
    flexibilityDayHide: 'hide',
    locker: false,
    amountLocker: '0.00',
    amountLockerError: false,
    amountLockerTextError: '',
    amountLockerHide: 'hide',
    attendanceLimit: false,
    typeLimitOptions: [
        {
            label: 'Diario', value: false,
        },
        {
            label: 'Mensual', value: true
        }
    ],
    limitAmount: '',
    limitAamountError: false,
    limitAamountTextArea: '',
    limitAamountHide: '',
    typeLimit: null,
    typeLimitError: '',
    typeLimitTextError: '',
    typeLimitHide: 'hide',
    inscription: false,
    amountInscription: '0.00',
    amountInscriptionError: false,
    amountInscriptionTextError: '',
    amountInscriptionHide: 'hide',
    partialPayments: false,
    dayPartialPayments: '',
    dayPartialPaymentsError: false,
    dayPartialPaymentsTextError: '',
    dayPartialPaymentsHide: 'hide',
    horario: false,
    optionDays: [
        { label: 'Lunes', value: 'Monday' },
        { label: 'Martes', value: 'Tuesday' },
        { label: 'Miercoles', value: 'Wednesday' },
        { label: 'Jueves', value: 'Thursday' },
        { label: 'Viernes', value: 'Friday' },
        { label: 'Sabado', value: 'Saturday' },
        { label: 'Domingo', value: 'Sunday' },
    ],
    arrayDaysAdditional: null,
    arrayDaysAdditionalError: '',
    arrayDaysAdditionalTextError: '',
    arrayDaysAdditionalHide: 'hide',
    collapsePenalizaciones:false,
    actionReducer: 0,
    arraySchedule: null,
    arrayScheduleError: '',
    arrayScheduleTextError: '',
    arrayScheduleHide: 'hide',
    registerSchedule: false,
    nameSchedule: '',
    nameScheduleError: false,
    nameScheduleTextError: '',
    nameScheduleHide: 'hide',
    intervalsMinute: ['00', '30'],
    hoursStart: 4,
    hoursEnd: 24,
    selectionsSchedule: [],
    scheduleTextError: '',    
    collapseDescuento: false,
    arrayDescuentos: null,
    arrayDescuentosError: '',
    arrayDescuentosTextError: '',
    arrayDescuentosHide: 'hide',
}