export const stateInitial = {
    loading: 'show',
    actionReducer: 0,

    name: '',
    nameError: false,
    nameTextError: '',
    nameHide: 'hide',

    description: '',
    descriptionError: false,
    descriptionTextError: '',
    descriptionHide: 'hide',

    amount: '0.00',
    amountError: false,
    amountTextError: '',
    amountHide: 'hide',

    arrayImpuesto: null,
    arrayImpuestoError: '',
    arrayImpuestoTextError: '',
    arrayImpuestoHide: 'hide',

    quotas: '',
    quotasError: false,
    quotasTextError: '',
    quotasHide: 'hide',

    corporateGroup: false,   

    giftedServices: '',
    giftedServicesError: false,
    giftedServicesTextError: '',
    giftedServicesHide: 'hide',

    acumulativeServices: '',
    acumulativeServicesError: false,
    acumulativeServicesTextError: '',
    acumulativeServicesHide: 'hide',

    icono: '',
    iconoError: '',
    iconoTextError: '',
    iconoHide: 'hide',

    nameIcono: '',
    nameIconoError: false,
    nameIconoTextError: '',
    nameIconoHide: 'hide',

    reserve: false,
    reserveWeb: false,
    reserveApp: false,
    reserveSede: false,

    expiration: false,
    expirationDate: new Date(),
    expirationDateError: "",
    expirationDateTextError: '',
    expirationDateHide: 'hide',

    partialPayments: false,
    dayPartialPayments: '',
    dayPartialPaymentsError: false,
    dayPartialPaymentsTextError: '',
    dayPartialPaymentsHide: 'hide',

    additionalDay: false,
    amountDayAdditional: '0.00',
    amountDayAdditionalError: false,
    amountDayAdditionalTextError: '',
    amountDayAdditionalHide: 'hide',
    optionDays: [
        { label: 'Lunes', value: 'Monday' },
        { label: 'Martes', value: 'Tuesday' },
        { label: 'Miercoles', value: 'Wednesday' },
        { label: 'Jueves', value: 'Thursday' },
        { label: 'Viernes', value: 'Friday' },
        { label: 'Sabado', value: 'Saturday' },
        { label: 'Domingo', value: 'Sunday' },
    ],
    arrayDaysAdditional: null,
    arrayDaysAdditionalError: '',
    arrayDaysAdditionalTextError: '',
    arrayDaysAdditionalHide: 'hide',

    collapsePenalizaciones: false,
    arrayPenalty: null,
    arrayPenaltyError: '',
    arrayPenaltyTextError: '',
    arrayPenaltyHide: 'hide',

    collapseMonitores: false,
    arrayScreens: null,
    arrayScreensError: '',
    arrayScreensTextError: '',
    arrayScreensHide: 'hide',

    horario: false,
    arraySchedule: null,
    arrayScheduleError: '',
    arrayScheduleTextError: '',
    arrayScheduleHide: 'hide',
    registerSchedule: false,
    nameSchedule: '',
    nameScheduleError: false,
    nameScheduleTextError: '',
    nameScheduleHide: 'hide',
    intervalsMinute: ['00', '30'],
    hoursStart: 4,
    hoursEnd: 24,
    selectionsSchedule: [],
    scheduleTextError: '',

    arrayDescuentos: null,
    arrayDescuentosError: '',
    arrayDescuentosTextError: '',
    arrayDescuentosHide: 'hide',
    collapseDescuento: false,

}