export const stateInitial = {
    loading: 'show',
    actionReducer: 0,
    name: "",
    nameError: false,
    nameTextError: '',
    nameHide: 'hide',
    arrayTypeIdentity: null,
    dni: "",
    dniError: false,
    dniTextError: '',
    dniHide: 'hide',
    web: "",
    webError: false,
    webTextError: '',
    webHide: 'hide',
    arrayCountry: null,
    arrayCountryError: '',
    arrayCountryTextError: '',
    arrayCountryHide: 'hide',
    arrayProvinceOption: [],
    arrayProvince: null,
    arrayProvinceError: '',
    arrayProvinceTextError: '',
    arrayProvinceHide: 'hide',
    arrayDistricOption: [],
    arrayDistric: null,
    arrayDistricError: '',
    arrayDistricTextError: '',
    arrayDistricHide: 'hide',
    collapseContacs: false,
    nombreContacto:'',
    nombreContactoError:false,
    nombreContactoTextError:'',
    nombreContactoHide:'hide',
    apellidoContacto:'',
    apellidoContactoError:false,
    apellidoContactoTextError:'',
    apellidoContactoHide:'hide',
    emailContacto:'',
    emailContactoError:false,
    emailContactoTextError:'',
    emailContactoHide:'hide',
    telefonoContacto:'',
    telefonoContactoError:false,
    telefonoContactoTextError:'',
    telefonoContactoHide:'hide',
    actionContacto: 0,
    keyContacto: -1,
}